#pragma once

#define ENCODERS_PAD_A { B5, B6 }
#define ENCODERS_PAD_B { B4, B2 }
#define ENCODER_RESOLUTION 4

#define OLED_DISPLAY_128X32

#define OLED_BRIGHTNESS 12
#define OLED_TIMEOUT 30000
#define OLED_FADE_OUT
