name: QMK Build
on:
  push:
    paths-ignore:
    - '**.md'
    - '**.py'
  workflow_dispatch:

jobs:
  build:
    name: Userspace build
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard: [dailycraft/wings42/rev2]
        keymap: [rafaelromao]
        
    steps:
    
    - name: Setup safe directory
      run: git config --global --add safe.directory '*'

    - name: Checkout qmk userspace
      uses: actions/checkout@v4
    
    - name: Get QMK Source 
      run: ./init_qmk.sh > qmk setup   

    - name: Setup QMK
      run: qmk setup -h $QMK_HOME   
      
    - name: Compile
      run: >
        qmk compile 
        -kb ${{ matrix.keyboard }}
        -km ${{ matrix.keymap }}

    - name: Archive firmware
      uses: actions/upload-artifact@main
      with:
        retention-days: 60
        name: ${{ matrix.keyboard }}
        path: |
          *.hex
          *.bin
          *.uf2

  purge:
    uses: filterpaper/scripts/.github/workflows/purge-workflow.yml@main
    with:
      purge-age: 5
      delete-all-completed: false
      delete-all-incomplete: false
